language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose up -d
  - docker-compose exec web python manage.py test
  - pipenv shell && python3.8 -m unittest utils/test_financials.py
